### ISSUE TITLE
Cannot run the project

### ISSUE THREAD

**Issue by anis1011** [Boriszn/DeviceManager.Api#12]
I cann't run the project, Please help me!!!
I have clone the project and then run update-database in PCM ,but the database isn't created in even though I use valid Connection String , What should I do?

**Comment by Boriszn** [comment]
Hi @anis1011. 

Could you please post your Errors, StackTrace. (or even screen shots with error details)

Thanks,
Boris

**Comment by anis1011** [comment]
![multi-tenant](https://user-images.githubusercontent.com/23692329/40110677-5a1d58b8-5920-11e8-98d5-fe0f822fba58.PNG)
I have clone the project and set the connection string in appsettings.json as "Server=.\\sqlexpress;Database=DeviceDb-ten2;Trusted_Connection=True;MultipleActiveResultSets=true"
and run the migration command:- Update-Database
It doesn't show any error list, simply stop the process as shown in the screenshot
Should I have to do extra configuration stuff to run the project?? Database is not simply updated  by running migration ?what should I do?

**Comment by Boriszn** [comment]
1. Please, try to connect to your local database with SqlServer Management Studio. (or any other IDE which able to connect to SQL Server)
2. If it it works then try to use connection string: `Data Source=(localdb)\\MSSQLLocalDB;Database=DeviceDb-ten2;Integrated Security=True;Trusted_Connection=True;MultipleActiveResultSets=True`

**Comment by anis1011** [comment]
Thanks for the quick response,
there is no problem in connecting my local database with ssms, I have tried using default connection string of the project with datasourse=(localdb)\\MSSQLLocalDB but still no change,
But for Testing purpose,I deleted migration folder,It shows this
![capture](https://user-images.githubusercontent.com/23692329/40114696-9cb6c58a-592d-11e8-98de-e03e93307cbf.PNG)

Here "Add-Migration Initial" command is also not working ... Please Help!!!

**Comment by anis1011** [comment]
All the NuGet Packages are fully Restored, other entity framework core commands like ( Get-Help about_EntityFrameworkCore )  are running ,I think that means EntityFrameworkCore Tools is successfully restored, Sorry I don't get about using developement branch .
My Visual Studio version is 15.5.3 and nuget version is 4.5.0 
Note: I simply clone the project and run the update-database, I didn't do any other works, Should I do other stuffs also ? Please Help!

**Comment by Boriszn** [comment]
@anis1011 about development, I meant try to switch version from `master` to `develpment` branch (So use this one https://github.com/Boriszn/DeviceManager.Api/tree/develop) and Run `Update-Database`.   

Also please check permission on your DbExpress database. Perhaps, it blocks EF db update somehow.

I will try to reproduce this issue on another PC, because I can't reproduce it on my own. (Everything works fine, Update, Add/Remove migration.)

I will get back to you soon...

**Comment by Boriszn** [comment]
@anis1011 I've tried to reproduce this issue on several other PCs. So, everything works fine...
Perhaps, you have wrong VS Environment variables configuration, this threads may help:
1. https://github.com/aspnet/EntityFrameworkCore/issues/7905 
2. https://github.com/aspnet/EntityFrameworkCore/issues/7540#issuecomment-286636108

Please try. (and tell me the results) :)

**Comment by anis1011** [comment]
Sometimes solutions are simpler than we think,  I have tried many options but solution is simple, I change aspnetcore version to 2.0 from 1.1 in .csproj file  ,and guess what? migration commands works . thanks @Boriszn  for your continuous support ,I might need your further support to understand the project as I am new to .net core world, thank you once again :) :)
with regards 
Anis

**Comment by Boriszn** [comment]
Nice. 👍 Your welcome ;) Glad that you manage to run it. 
Sure, also you may found **`[this article useful.](https://medium.com/@boriszn/building-multi-tenant-web-api-using-dot-net-core-and-best-practices-8dce439bfae7)`**
