### ISSUE TITLE
UOW - Stored Proc

### ISSUE THREAD

**Issue by arunprasathv** [Boriszn/DeviceManager.Api#14]
@Boriszn 
I would like to change UOW to call stored proc which is not tied to any repository.  thinking to create a repository for stored proc and call FromSql. please let me know otherwise.

Thanks

**Comment by Boriszn** [comment]
Hi @arunprasathv 

1. You don't have to change UoW to execute raw sql. 
2. You just need to add following method to generic repository (`Repository.cs`):

```C#
       public IQueryable<T> FromSql(string sqlQuery)
        {
            return this.dbSet.FromSql(sqlQuery);
        }
```
3. Execute it from service class or from another specific repository like:
```C#
...
var users = userRepository.FromSql(""EXECUTE dbo.GetUsers").ToList();
....
```

Please be aware that using raw sql is good when you have legacy code ;)

**Comment by arunprasathv** [comment]
Hi @Boriszn 

I already have this method in repository.cs , the stored proc will not be related to any repository as it might get results from a couple of tables.  Do I need to create a repository/model that matches SPs response and use it to call the SP. 

public IQueryable<T> FromSql(string query, params object[] parameters)
        {
            return this.dbSet.FromSql(query, parameters);
        }

**Comment by Boriszn** [comment]
Hi @arunprasathv 

Yeah better would be create custom repository derived from generic one and use this in Business Layer.
And you need model ofc.

**Comment by arunprasathv** [comment]
@Boriszn Yep. Something like this makes sense. Thanks.

**Comment by Boriszn** [comment]
Hi @arunprasathv  Welcome. Let me know if you need more info ;)
