### ISSUE TITLE
IdentityServer4

### ISSUE THREAD

**Issue by rudreshgp** [Boriszn/DeviceManager.Api#26]
Hi, @Boriszn Good day!

I am going through IdentityServer4 samples and have following doubts
1. Do we need to support Forms Authentication?
2. Use external authentication systems like Google, Facebook?

**Comment by rudreshgp** [comment]
Hi, @Boriszn I added oauth2 bearer authentication to the project and now through Swagger-UI we can log in. Also, roles/claims support is added. I am now working on updating docker files as I have used sample project from idenityserver4 repository project for the identity server.

**Comment by rudreshgp** [comment]
So in docker authentication is working but authorization is failing. I will try to fix the same.

**Comment by Boriszn** [comment]
Hi, @rudreshgp. 

Thank you a lot for the question and input.
I would say, the first priority is **bearer** token. 
However, Google, and Facebook (or at least one of them) would be nice to have. (as configurative option, for example) 

Best Regards,
Boris

**Comment by rudreshgp** [comment]
I have implemented Bearer authentication. I will create a pull request this weekend.

**Comment by Boriszn** [comment]
@rudreshgp  Regarding Identity Server: Have you created Identity Server repository somewhere or you using some Identity Server online, as as service ? 
Regarding docker issue, could please explain the issue (with authorization) in detail ;) ? 

Thanks,
Boris

**Comment by rudreshgp** [comment]
Currently, I am using [IdentityServer4 server project](https://identityserver4.readthedocs.io/en/latest/quickstarts/3_interactive_login.html) provided by IdentityServer4 samples. But is it better to use an external service?

**Comment by rudreshgp** [comment]
The issue with docker the client(Device Manager API) is not able to verify the authority which issues the token, Even both client and server are connected using localhost.

**Comment by rudreshgp** [comment]
Hey, I fixed the issue by using the static-ip address for each container in the `docker-compose` file.
Authentication & Authorization both are working with or without docker.

Only, thing currently not working are [Device-Api Test](https://github.com/rudreshgp/DeviceManager.Api/blob/IdentityServerIntegration/test/DeviceManager.Api.UnitTests/Api/DevicesApiTests.cs) because they are also building the request context.

I will try to fix the same. 

I have pushed the code to a new branch in my forked repository by the name [Identity Server Integration](https://github.com/rudreshgp/DeviceManager.Api/tree/IdentityServerIntegration). You can clone it and run. 

Users can be configured in the [Config](https://github.com/rudreshgp/DeviceManager.Api/blob/IdentityServerIntegration/src/DeviceManager.IdentityServer/Config.cs) file.

**Comment by Boriszn** [comment]
Hey @rudreshgp that's awesome. 

Don't forget to put all you findings in the readme file.

I'm not completely get what is issue about. :) So you can't connect to the Identity server from docker container, Right ?  If yes then you should not use `localhost`  names etc from the container and you should use IP.
I had same issue with SQL Server local instance (or express).

Regarding Identity Server. It is right, but I would like to create my own Identity Server Repository based on examples and templates, [they provided here. IdentityServer4.Templates](https://github.com/IdentityServer/IdentityServer4.Templates) also would like to get it work with Azure Active directory.

**Comment by rudreshgp** [comment]
Yes. even though they connect using `localhost`. The API can't verify identity authority while running in the container.

**Comment by Boriszn** [comment]
Hi @rudreshgp 

I think, creating Docker Network (or network bridge) may help. 
Here the link with same issue: 
- https://stackoverflow.com/questions/43911536/how-can-i-use-identityserver4-from-inside-and-outside-a-docker-machine

I will try also tackle this issue in the future.

**Comment by rudreshgp** [comment]
@Boriszn do I need to add (https://github.com/IdentityServer/IdentityServer4.Templates#dotnet-new-is4ef)[Identity server - ef] ??

**Comment by rudreshgp** [comment]
Hi, @Boriszn I have updated the project using templates you mentioned. 

Also, I have added new claims by the name `tenant_id` which stores tenant id for users. 

The users having `admin` role can access data from any tenant. Non `admin` users need a claim by the name `tenant_id` and value being the tenant they belong. Users now can't access data from other tenants. 

Currently, data is stored in a local database file.

While running in docker compose it's facing the same issue as before because redirect URLs stored in the database are pointing to localhost address. I will try to fix the same.

**Comment by rudreshgp** [comment]
Hey, @Boriszn I solved the issue using hosts file in windows.

According to this [https://stackoverflow.com/questions/42866013/docker-toolbox-localhost-not-working](StackOverflow question), in Windows, there are issues present while using `localhost` within container services. We should use the `service name`. 

Hence, I defined the following two values in the `hosts` file present in 

> C:\Windows\System32\drivers\etc\hosts.

`127.0.0.1 devicemanager.api`
`127.0.0.1 devicemanager.identityserver`

Then modified `docker-compose.override.yml` file with below settings

```version: '3.4'

services:
  devicemanager.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AUTHENTICATION_AUTHORITY=http://devicemanager.identityserver:5000
      - ASPNETCORE_URLS=http://0.0.0.0:5001
    ports:
      - "5001:5001"
  devicemanager.identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - SWAGGER_CLIENT=http://devicemanager.api:5001
    ports:
      - "5000:5000"
```

Then changed `launchsettings.json`

```
"profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "AUTHENTICATION_AUTHORITY": "http://devicemanager.identityserver:5000/"
      },
      "applicationUrl": "http://devicemanager.api:5001"
    },
    "DeviceManagerApi": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "AUTHENTICATION_AUTHORITY": "http://devicemanager.identityserver:5000/"
      },
      "applicationUrl": "http://devicemanager.api:5001"
    },
    "Docker": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "http://devicemanager.api:5001/swagger"
    }
  }
```
Now the authentication is happening without any static IP configuration. The configuration works with/without `docker-compose`.

One thing is running docker images need to be stopped when the user wants to run outside docker using `docker stop image_id`.

TODO: 
Currently, the identity server is using `sqlite` as the database. 
Add more clients for the console app.
Allow user to send queries from postman/restlet client

**Comment by rudreshgp** [comment]
`bridge` network doesn't work for windows.

**Comment by Boriszn** [comment]
Hi @rudreshgp 

Thank you a lot for the input. 
I have some questions: 
1. Are you using docker-toolbox ? If yes you shouldn't because it is legacy solution, you should switch to 
Docker for Windows: https://docs.docker.com/docker-for-windows/install/ Below is warn message from docker portal: 
```
Docker Toolbox is for older Mac and Windows systems that do not meet the requirements of Docker Desktop for Mac and Docker Desktop for Windows. We recommend updating to the newer applications, if possible.
```
2. In the Hosts you are using same IP for both services ? If yes how it can work then ? 
3. Identity Server aslo allows you to use SQL Server (LocalDb, Express, etc) http://docs.identityserver.io/en/latest/quickstarts/7_entity_framework.html I think It would be better to use it, isn't it ?.

**Comment by rudreshgp** [comment]
@Boriszn yes I am using Docker Toolbox for windows. Currently, need to update database settings to connect to local SQL express database. 

I have created a [Identity Server Integration](https://github.com/rudreshgp/DeviceManager.Api/tree/IdentityServerIntegration) branch in my fork.

**Comment by Boriszn** [comment]
Hey @rudreshgp . 

Thank you a lot, I see the point. 

As I understood,  Connection to SQL Express/`(local)` DB from Docker container, not an issue anymore, Right ?

**Comment by rudreshgp** [comment]
The solution is to use the way you mentioned, by entering the IP Address. 
One way we can handle this is by entering the IP address in `.env` file and enabling remote connections.

**Comment by rudreshgp** [comment]
@Boriszn 
🙌 🙌 🙌 🙌 🙌 

Now unit tests are running under Authentication. Authentication is an add-on feature using the compiler switch `UseAuthentication`. I will add new test cases for `Authentication` and update the `README.md`. Then create a new pull request.

**Comment by Boriszn** [comment]
Hi @rudreshgp  

Sounds quite impressive !!! ;) You overcome all issues. :)) Thank you a so much. 
I've seen your PR, I will take a look. 

Best Regards,
Boris
