### ISSUE TITLE
EF Global Query filters

### ISSUE THREAD

**Issue by rudreshgp** [Boriszn/DeviceManager.Api#29]
Hi, @Boriszn according to this [task](https://github.com/Boriszn/DeviceManager.Api/projects/1#card-13616823) you are saying we should add `query filter` for `id`. I am quite confused about this task.

But, what is the use of defining query filter for id?? Global Query filters like `deleted` make sense.

**Comment by Boriszn** [comment]
Hi @rudreshgp 
I would like to Re-Create (Or even better add additional option) for tenant switching using EF Core filter. I've updated the task added link.
Could you please give me example and detail explanation regarding `delete` filter. I didn't get it this option.

**Comment by rudreshgp** [comment]
`Tenant Switching` will be useful in case if we want to use the same database for all tenants right??

Regarding `deleted`, I thought we can maintain deleted records using `deleted` property and filter them in each query using `deleted` filter.

**Comment by Boriszn** [comment]
Hi @rudreshgp 

About delete this is good idea. But for me this is not clear enough . So you going to mark entity `deleted` but no keep data in DB, right ?

**Comment by rudreshgp** [comment]
As per my understanding, you will keep all records in the database and add an extra ´deleted´ field in the table to indicate the record is not valid.
