### ISSUE TITLE
Dapper incorporation

### ISSUE THREAD

**Issue by rudreshgp** [Boriszn/DeviceManager.Api#30]
@Boriszn I was going through the code to check how to incorporate `Dapper`. It looks like right from `ContextFactory` we need to add new classes to accommodate `Dapper`.

**Comment by Boriszn** [comment]
@rudreshgp 

I've created this repository with complete example of using dapper: https://github.com/Boriszn/Dapp.API 

My original plan using EF with Dapper:
- Is having 2 unit of works for EF and Dapper (see example of UoW in repository below)
- Retrieving `SqlConnection` from context factory 
- Injecting dapper UoW alongside with EF , into service.

**Comment by rudreshgp** [comment]
Hi, @Boriszn Good day!

I have created a Generic dapper repository capable of generating dynamic queries for insert and get based on an attribute and it's working. I will create a pull request over the weekend after adding a few unit tests.

**Comment by rudreshgp** [comment]
Hey, @Boriszn I have incorporated Dapper and pushed the code to my development branch. 

Have a look once. I need to update README and add one or two test cases more. 

Dapper is able to fetch all records, fetch one record, create a new record using generics.
